keys:
  - &admin_samuel age1lpn0g0yrz5svwlhk0us6nurw666v2w5ru9qe583pwtdnqhpcn9fqj8zd0q
  - &monster age1c2xa8fmslcl4k6mc3gcn7kpc7z6x58fqseuy8g2qdgv9r3w3j3qqlmj3l7
  - &hyper age13zfzhzhf75k7fjvs568yd52qegk6ezer3d9ra9r4js4dae69x9jq07nnut
  - &pikachu age1f97uwcswnz8z3vn3jngejk8a6r3075pajmp7ze8rccvpkkhrhcmsny2nlp
  - &centrium age17278qs9exjzhjvu4fddppdnvwht34r3ffekzse02uc4hjfat6dps7ep73l

creation_rules:
  - path_regex: ^secrets/.*$
    key_groups:
      - age:
          - *admin_samuel
          - *monster
          - *hyper
          - *pikachu
          - *centrium
