name: "CI"

on:
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
  push:
    branches: [ master ]
    paths:
      - '**.nix'
      - 'flake.lock'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: experimental-features = nix-command flakes repl-flake
    - uses: cachix/cachix-action@v12
      with:
        name: otavio-nix-config
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix flake check

  nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixosConfiguration:
          - centrium
          - hyper
          - pikachu
    steps:
    - run: sudo apt-get clean
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v22
      with:
        nix_conf: experimental-features = nix-command flakes repl-flake
    - run: nix -Lv build ".#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel"
