name: "CI"

on:
  pull_request:
    paths:
      - '**.nix'
      - 'flake.lock'
  push:
    branches: [ master ]
    paths:
      - '**.nix'
      - 'flake.lock'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v29
      with:
        nix_conf: experimental-features = nix-command flakes repl-flake
    - uses: cachix/cachix-action@v15
      with:
        name: ossystems-lab
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Install SSH Private Key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: nix flake check

  nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixosConfiguration:
          - centrium
          - hyper
          - pikachu
    steps:
    - run: sudo apt-get clean
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v29
      with:
        nix_conf: experimental-features = nix-command flakes repl-flake
    - uses: cachix/cachix-action@v15
      with:
        name: ossystems-lab
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Install SSH Private Key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: nix -Lv build ".#nixosConfigurations.${{ matrix.nixosConfiguration }}.config.system.build.toplevel"
